name: Build domain list

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: build-domain-list
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Checkout domain list
        uses: actions/checkout@v6
        with:
          repository: v2fly/domain-list-community
          path: domain-list-community

      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - run: npm ci
      - run: npm run build

      - name: Push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"

          rm -rf public/surge
          rm -rf public/clash

          mkdir -p public

          git add public
          git commit -m "chore: update domain list" || echo "chore: no changes to commit"
          git push origin main
